name: pytests in Docker-compose Actions Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker images
      run: docker-compose build
    
    - name: start the Docker containers
      run: docker-compose --profile testing up -d
    
    - name: Install pytest
      run: pip install pytest
    
    - name: Test with pytest
      run: coverage run -m test_idp.py  -v -s 
    
    - name: Generate Coverage Report  
      run: coverage report -m
